### ISSUE TITLE
Have plan to support for web ReadableStream instead of filename for big file?

### ISSUE THREAD

**Issue by irelance** [junka/ffmime#1]
or have plan to split wasm into piece by extname or file magic number?
:)

**Comment by junka** [comment]
Hi irelance,

Thanks for your interest.

> Have plan to support for web ReadableStream instead of filename for big file?

So you are trying to probe a stream than a file. If it is the case, some kind of metadata over http would be prefered.
Please describle the usecase that you want to probe a stream. No plan from mine side.

---

> or have plan to split wasm into piece by extname or file magic number?

No, AFAIK ffmpeg will only read part of the file and rate scores for all media formats. Then it will take highest one as the right format.

**Comment by irelance** [comment]
thanks
